# Service A: app.yaml
service: service-b # Or 'default' if this is your main service
runtime: nodejs20 # Or nodejs18, nodejs16 etc.
instance_class: F1 # Cost-effective starting point

# Environment variables (migrate from .env)
env_variables:
  # NODE_ENV: production # Good practice
  # GEMINI_API_KEY: "YOUR_ACTUAL_GEMINI_API_KEY" # PASTE ACTUAL KEY HERE (See Note below)
  GOOGLE_APPLICATION_CREDENTIALS: "./functionsinjs-firebase-adminsdk-qpa97-44a2d86f99.json"
  GCS_BUCKET_NAME: "gs://functionsinjs.firebasestorage.app"
  PORT: 3001 
  # PORT: 8080 # GAE sets this automatically, but explicit doesn't hurt

# Optional: Scaling settings (defaults are usually fine to start)
# automatic_scaling:
#   min_instances: 0
#   max_instances: 1
#   target_cpu_utilization: 0.65

# Handlers are often automatic for Node.js Express apps
# handlers:
# - url: /.*
#   script: auto